@protocol=http://
@host=localhost
@port=:5000
@baseUrl={{protocol}}{{host}}{{port}}

### Test get users
GET {{baseUrl}}/players HTTP/1.1


### Test create user
POST {{baseUrl}}/createPlayer HTTP/1.1
content-type: application/json

{
    "pseudo": "patricey0",
    "password": "123qwe"
}

### Test login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "pseudo": "patricey0",
    "password" : "123qwe"
}

### Test delete user
DELETE {{baseUrl}}/player/2 HTTP/1.1
content-type: application/json


### Test validation token
GET {{baseUrl}}/loginCheck/7 HTTP/1.1
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjo3LCJpYXQiOjE2NDY2NTE2ODgsImV4cCI6MTY0NjczODA4OH0.Hi6e3cuJR_K7X4RRoGRLDBVsWkB4uirMeNd9OdkmGaw"