@protocol=http://
@host=localhost
@port=:5000
@baseUrl={{protocol}}{{host}}{{port}}

### Test get users
GET {{baseUrl}}/players HTTP/1.1


### Test create user
POST {{baseUrl}}/createPlayer HTTP/1.1
content-type: application/json

{
    "pseudo": "patricey0",
    "password": "123qwe"
}

